version: "3.8"
services:
  webserver:
    container_name: pet-adoption-backend-php
    image: webdevops/php-nginx-dev:8.2-alpine
    working_dir: /app
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
        SECRET: ${SECRET}
        CATS_API_TOKEN: ${CATS_API_TOKEN}
        DOGS_API_TOKEN: ${DOGS_API_TOKEN}
        WEB_DOCUMENT_ROOT: ${WEB_DOCUMENT_ROOT}
        PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_HOST: "pet-adoption-database-php"

  mysql:
    container_name: pet-adoption-database-php
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
